steps:
  #Package Install
  - name: "gcr.io/cloud-builders/npm:node-${_NODE_VERSION}"
    args: ["install"]

  #Unit test
  - name: "gcr.io/cloud-builders/npm:node-${_NODE_VERSION}"
    args: ["test"]

  #Build image
  - name: "gcr.io/cloud-builders/docker"
    dir: .
    args: ["build", "-t", "gcr.io/$PROJECT_ID/${_IMAGE_NAME}:${_TAG}", "."]

  #Push image
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/${_IMAGE_NAME}"]

  #Deploy image
  - name: "gcr.io/cloud-builders/gcloud"
    id: "deploy-cloud-run"
    args:
      [
        "beta",
        "run",
        "deploy",
        "${_SERVICE_NAME}",
        "--image",
        "gcr.io/$PROJECT_ID/${_SERVICE_NAME}",
        "--region",
        "${_REGION}",
        "--platform",
        "managed",
        "--allow-unauthenticated",
      ]

substitutions:
  _REGION: asia-northeast1
  _SERVICE_NAME: nextjs-on-cloudrun
  _IMAGE_NAME: nextjs-on-cloudrun
  _TAG: latest
  _NODE_VERSION: 18.17.1

options:
  logging: CLOUD_LOGGING_ONLY